Expose connection pool size to generic database
jenkinsci/database-plugin pull request #60
Opened 2021-05-01 20:18 UTC by jamesnswithers

[JENKINS-65527]
Exposed connection pool size properties in an advanced section.
Initial Size, Max Total, Min Idle and Max Idle all provided with defaults as per commons dbcp.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-05-01 20:23 UTC, timja commented on src/main/java/org/jenkinsci/plugins/database/GenericDatabase.java
> +    public GenericDatabase(String url, String driver, String username, Secret password,
Please use data bound setters for optional parameters https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/#constructor-vs-setters

2021-05-24 07:28 UTC, timja requested changes

2021-05-24 07:28 UTC, timja commented on src/main/resources/org/jenkinsci/plugins/database/GenericDatabase/config.groovy
> +f.entry(field:"driver",title:_("JDBC Driver Class"), help: descriptor.getHelpFile('driver')) {
why did you add the explicit help? If I remove it it works just fine?

2021-05-24 07:28 UTC, timja commented on src/main/resources/org/jenkinsci/plugins/database/GenericDatabase/config.groovy
> +    f.entry(field: "initialSize", title: _("Initial Size"), help: descriptor.getHelpFile('initialSize')) {
explicit help should not be used in general, just put the file in the right place which you have

2021-05-24 07:43 UTC, jamesnswithers commented on src/main/resources/org/jenkinsci/plugins/database/GenericDatabase/config.groovy
> +f.entry(field:"driver",title:_("JDBC Driver Class"), help: descriptor.getHelpFile('driver')) {
I don't remember, have tested as suggested and all fine, cheers

2021-05-24 07:46 UTC, timja approved these changes

2021-05-24 07:47 UTC, merged